openapi: 3.0.0
info:
  title: Records API specs
  description: Records API specs
  version: 0.0.1

paths:
  /:
    post:
      summary: Returns a list of records
      description: Returns a list of records based on filters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                startDate:
                  type: string
                  format: date
                endDate:
                  type: string
                  format: date
                minCount:
                  type: number
                maxCount:
                  type: number
      responses:
        '200':
          description: Response
